# Generated by Django 5.1.2 on 2024-11-27 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_karma'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='api_key',
            field=models.CharField(default='default-api-key', max_length=255),
        ),
    ]
