# Generated by Django 5.1.2 on 2024-11-28 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='banner_perfil_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='imagen_perfil_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
