# Generated by Django 5.1.2 on 2024-12-02 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_banner_perfil_url_profile_imagen_perfil_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='api_key',
            field=models.CharField(default='63be6e93-02d7-44ee-8954-481fa87e008a', max_length=255),
        ),
    ]
