# Generated by Django 5.1.2 on 2024-12-02 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_profile_api_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='api_key',
            field=models.CharField(default='default-api-key', max_length=255),
        ),
    ]
