# Generated by Django 5.1.2 on 2024-11-05 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_submission_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='submission_type',
            field=models.CharField(default='text', editable=False, max_length=10),
        ),
    ]
