# Generated by Django 5.1.2 on 2024-11-06 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0003_submission_submission_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
