# Generated by Django 5.1.2 on 2024-11-06 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0004_alter_submission_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='author',
            field=models.CharField(default='Anonymous', max_length=50),
        ),
    ]
