# Generated by Django 5.1.2 on 2024-11-06 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0005_submission_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
