# Generated by Django 5.1.2 on 2024-11-06 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0006_submission_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='text',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
