# Generated by Django 5.1.2 on 2024-11-10 16:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0009_submission_hidden_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='voted_by',
            field=models.ManyToManyField(blank=True, related_name='voted_submissions', to=settings.AUTH_USER_MODEL),
        ),
    ]
