# Generated by Django 5.1.2 on 2024-11-28 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0011_submission_favorite_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='url',
            field=models.URLField(blank=True, default='', max_length=500, null=True),
        ),
    ]
